import { CartProvider } from "@/contexts/CartContext";
import Providers from "../providers";
import WhatsAppButton from "@/components/WhatsAppButton";
import Navbar from "../navbar";
import Footer from "../footer";
import {
  getAddressByCatalog,
  getCatalogBySlug,
} from "@/services/catalog/catalog-controller";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";

type Props = {
  params: Promise<{ catalog_slug: string }>;
  children: React.ReactNode;
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }: Props) {
  const { catalog_slug } = await params;

  const catalog = await getCatalogBySlug(catalog_slug);

  if (!catalog) {
    return (
      <div className="min-h-screen">
        Erro inesperado na página, o catálog não existe!!
      </div>
    );
  }

  const address = await getAddressByCatalog(catalog.id);

  return (
    <html
      lang="en"
      style={{
        ["--primary" as any]: catalog.theme_color,
      }}
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <CartProvider>
            <Navbar {...{ catalog }} />
            <main className="flex-1">{children}</main>
            <Footer {...{ catalog, address }} />
            <WhatsAppButton />
          </CartProvider>
        </Providers>
      </body>
    </html>
  );
}
